export const SET_MODE_TRUE = 'SET_MODE_TRUE'
export const SET_MODE_FALSE = 'SET_MODE_FALSE'

export const CLICKED_BUTTON_TRUE = 'CLICKED_BUTTON_TRUE'
export const CLICKED_BUTTON_FALSE = 'CLICKED_BUTTON_FALSE'
